// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           28
// Async Callback (empty):               1
// Total number of exported functions:  31

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    work_escrow
    (
        init => init
        upgrade => upgrade
        activateAgreement => activate_agreement
        fundEmployerRunway => fund_employer_runway
        fundWorkerBond => fund_worker_bond
        topUpRunway => top_up_runway
        claimRecurringPay => claim_recurring_pay
        submitMilestone => submit_milestone
        approveMilestone => approve_milestone
        rejectMilestone => reject_milestone
        autoApproveMilestone => auto_approve_milestone
        depositRevenue => deposit_revenue
        requestTerminate => request_terminate
        finalizeTerminate => finalize_terminate
        withdrawClaimable => withdraw_claimable
        setProtocolFeeBps => set_protocol_fee_bps
        setReferralShareBps => set_referral_share_bps
        setTreasury => set_treasury
        setMinUptimeScore => set_min_uptime_score
        setRiskParams => set_risk_params
        setPaused => set_paused
        setOwner => set_owner
        getAgreement => get_agreement
        getAgreementFinancials => get_agreement_financials
        getMilestone => get_milestone
        getAgentReputation => get_agent_reputation
        getProtocolStats => get_protocol_stats
        getConfig => get_config
        getClaimable => get_claimable
        isOfferConsumed => is_offer_consumed
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
