// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           23
// Async Callback (empty):               1
// Total number of exported functions:  26

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    job_board_core
    (
        init => init
        upgrade => upgrade
        createJob => create_job
        apply => apply
        proposeOffer => propose_offer
        counterOffer => counter_offer
        rejectOffer => reject_offer
        withdrawOffer => withdraw_offer
        acceptOffer => accept_offer
        cancelJob => cancel_job
        expireJob => expire_job
        setMinUptimeScore => set_min_uptime_score
        setMaxCounteroffersPerApplication => set_max_counteroffers_per_application
        setMaxInvitesPerJob => set_max_invites_per_job
        setPaused => set_paused
        setOwner => set_owner
        getJob => get_job
        getApplication => get_application
        getOffer => get_offer
        getApplications => get_applications
        getOffers => get_offers
        getAcceptedOffer => get_accepted_offer
        isInviteAllowed => is_invite_allowed
        getBoardStats => get_board_stats
        getConfig => get_config
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
